[package]
name = "crawl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
serde = "1.0.209"
serde_json = "1.0.127"
anyhow = "1.0.86"
dotenv = "0.15.0"
reqwest = "0.12.7"

booru = { path = "../.." }
