[package]
name = "get_posts"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = "1.0.209"
serde_json = "1.0.127"
anyhow = "1.0.86"
dotenv = "0.15.0"
reqwest = "0.12.7"
image = "0.24.9"
imgcatr = "0.1.4"

booru = { path = "../.." }
