[package]
name = "styles"
version = "0.1.0"
edition = "2021"

[dependencies]
booru = { path = "../.." }
hf = { path = "../../lib/hf" }

anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
futures = "0.3.31"
image = "0.25.5"
indicatif = { version = "0.17.9", features = ["futures"] }
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
